" Generated by vim-plug
" Mon Jul  8 22:26:53 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bluloco.nvim'].commit = 'e7586def35c3584f1cc71fecf3e89e53dc4a40c6'
silent! let g:plugs['catppuccin'].commit = '2d3419c2aead379b7d1854d32458f20ffaa58562'
silent! let g:plugs['coc.nvim'].commit = '51692dc1d148f67f18573d1afeb4724dc5a06506'
silent! let g:plugs['dracula'].commit = '8d8bddb8814c3e7e62d80dda65a9876f97eb699c'
silent! let g:plugs['fzf-lua'].commit = '975534f4861e2575396716225c1202572645583d'
silent! let g:plugs['gruvbox'].commit = 'f1ecde848f0cdba877acb0c740320568252cc482'
silent! let g:plugs['hop.nvim'].commit = '1a1eceafe54b5081eae4cb91c723abd1d450f34b'
silent! let g:plugs['local-highlight.nvim'].commit = 'ae3ada3a332128b1036c84c8587b9069891c63da'
silent! let g:plugs['lualine.nvim'].commit = '6a40b530539d2209f7dc0492f3681c8c126647ad'
silent! let g:plugs['lush.nvim'].commit = '7c0e27f50901481fe83b974493c4ea67a4296aeb'
silent! let g:plugs['neo-tree.nvim'].commit = '206241e451c12f78969ff5ae53af45616ffc9b72'
silent! let g:plugs['night-owl.nvim'].commit = '131641a516085c5b3cacc8022581902e9f2f14af'
silent! let g:plugs['nord.nvim'].commit = '80c1e5321505aeb22b7a9f23eb82f1e193c12470'
silent! let g:plugs['nui.nvim'].commit = '61574ce6e60c815b0a0c4b5655b8486ba58089a1'
silent! let g:plugs['nvim-cokeline'].commit = '8145048ae68e05f31979c13b0adf7aa99f04f4c0'
silent! let g:plugs['nvim-comment'].commit = 'e9ac16ab056695cad6461173693069ec070d2b23'
silent! let g:plugs['nvim-surround'].commit = 'ec2dc7671067e0086cdf29c2f5df2dd909d5f71f'
silent! let g:plugs['nvim-treesitter'].commit = '53c79ddc28b0df3263d629f5e20c9283b05841ca'
silent! let g:plugs['nvim-web-devicons'].commit = 'c0cfc1738361b5da1cd0a962dd6f774cc444f856'
silent! let g:plugs['oceanic-next'].commit = '09833f72d5ba23de2e8bcae18f479f326f5f677a'
silent! let g:plugs['plenary.nvim'].commit = 'a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683'
silent! let g:plugs['undotree'].commit = '56c684a805fe948936cda0d1b19505b84ad7e065'
silent! let g:plugs['vim-better-whitespace'].commit = '86a0579b330b133b8181b8e088943e81c26a809e'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'
silent! let g:plugs['which-key.nvim'].commit = 'af4ded85542d40e190014c732fa051bdbf88be3d'

PlugUpdate!
