" Generated by vim-plug
" Tue Nov 26 11:27:13 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bluloco.nvim'].commit = '9ac4ad3a7b702035ff70b1f1d70de548130bb787'
silent! let g:plugs['catppuccin'].commit = 'faf15ab0201b564b6368ffa47b56feefc92ce3f4'
silent! let g:plugs['coc.nvim'].commit = 'ebe7a08ece39a7ea867cb43497ce83ad722b6f07'
silent! let g:plugs['dracula'].commit = 'e6128ec3923b92bb2b16e81b4a0f04ed0308038e'
silent! let g:plugs['fzf-lua'].commit = 'ce978474e406f4faacd2e66ec35d93b9e8ae069e'
silent! let g:plugs['gruvbox'].commit = 'f1ecde848f0cdba877acb0c740320568252cc482'
silent! let g:plugs['hop.nvim'].commit = '1a1eceafe54b5081eae4cb91c723abd1d450f34b'
silent! let g:plugs['local-highlight.nvim'].commit = 'ae3ada3a332128b1036c84c8587b9069891c63da'
silent! let g:plugs['lualine.nvim'].commit = '2a5bae925481f999263d6f5ed8361baef8df4f83'
silent! let g:plugs['lush.nvim'].commit = '45a79ec4acb5af783a6a29673a999ce37f00497e'
silent! let g:plugs['neo-tree.nvim'].commit = '42caaf5c3b7ca346ab278201151bb878006a6031'
silent! let g:plugs['night-owl.nvim'].commit = '86ed124c2f7e118670649701288e024444bf91e5'
silent! let g:plugs['nord.nvim'].commit = '80c1e5321505aeb22b7a9f23eb82f1e193c12470'
silent! let g:plugs['nui.nvim'].commit = 'b58e2bfda5cea347c9d58b7f11cf3012c7b3953f'
silent! let g:plugs['nvim-cokeline'].commit = 'adfd1eb87e0804b6b86126e03611db6f62bb2909'
silent! let g:plugs['nvim-comment'].commit = 'e9ac16ab056695cad6461173693069ec070d2b23'
silent! let g:plugs['nvim-surround'].commit = 'dca2e998ff26681ee422b92c6ed39b3d2908d8a9'
silent! let g:plugs['nvim-treesitter'].commit = '28591731d84c2fc18ddda60e1d53da24c31c4987'
silent! let g:plugs['nvim-web-devicons'].commit = 'edbe0a65cfacbbfff6a4a1e98ddd60c28c560509'
silent! let g:plugs['oceanic-next'].commit = '09833f72d5ba23de2e8bcae18f479f326f5f677a'
silent! let g:plugs['plenary.nvim'].commit = '2d9b06177a975543726ce5c73fca176cedbffe9d'
silent! let g:plugs['undotree'].commit = '78b5241191852ffa9bb5da5ff2ee033160798c3b'
silent! let g:plugs['vim-better-whitespace'].commit = '86a0579b330b133b8181b8e088943e81c26a809e'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'
silent! let g:plugs['which-key.nvim'].commit = 'b9684c6ec54d8a8452bdcf0d613c7ad0223fc3fe'
silent! let g:plugs['zoxide.vim'].commit = 'b1e70b6fc1682a83929aee63680d2b43456fe9a5'

PlugUpdate!

