" Generated by vim-plug
" Tue Nov 21 10:40:58 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S ~/.config/nvim/snapshot.vim

silent! let g:plugs['bluloco.nvim'].commit = '37795f21b48df8c12b478518af53f3dddb9014f7'
silent! let g:plugs['catppuccin'].commit = 'a8dfb969e76d1a0752d98b5347be9ffb9bca9592'
silent! let g:plugs['coc.nvim'].commit = '1d3c525e2d6af0c07ed19fa7a5016ffc6a9e8421'
silent! let g:plugs['dracula'].commit = '6495b4ff40479ec7705addb4ea800ec308026648'
silent! let g:plugs['fzf-lua'].commit = '99684a6c07da13ba49f62cfaf309dbce285247a7'
silent! let g:plugs['gruvbox'].commit = 'f1ecde848f0cdba877acb0c740320568252cc482'
silent! let g:plugs['hop.nvim'].commit = '1a1eceafe54b5081eae4cb91c723abd1d450f34b'
silent! let g:plugs['impatient.nvim'].commit = '47302af74be7b79f002773011f0d8e85679a7618'
silent! let g:plugs['local-highlight.nvim'].commit = 'b5c45c0383f814b7b1498dd53fdd840750d50243'
silent! let g:plugs['lualine.nvim'].commit = '2248ef254d0a1488a72041cfb45ca9caada6d994'
silent! let g:plugs['lush.nvim'].commit = '966aad1accd47fa11fbe2539234f81f678fef2de'
silent! let g:plugs['marks.nvim'].commit = '76aca5069c5ce5c0099e30168649e6393e494f26'
silent! let g:plugs['night-owl.vim'].commit = '783a41a27f7fe55ed91d1ec0f0351d06ae17fbc7'
silent! let g:plugs['nord.nvim'].commit = '0a22a387c92bb3b46e3d245522712ae7497bec38'
silent! let g:plugs['nvim-cokeline'].commit = '3682c78e0b727c12fb84405b694c14cc1af4d64b'
silent! let g:plugs['nvim-comment'].commit = 'e9ac16ab056695cad6461173693069ec070d2b23'
silent! let g:plugs['nvim-surround'].commit = '0855a89e00a5822c3a482a82e5223fcf2e9ede13'
silent! let g:plugs['nvim-tree.lua'].commit = '8c534822a7d16c83cf69928c53e1d8a13bd2734a'
silent! let g:plugs['nvim-treesitter'].commit = '7da3cb6323d1e1fbfc4d7dc05cac74946458b8a0'
silent! let g:plugs['nvim-web-devicons'].commit = 'cdbcca210cf3655aa9b31ebf2422763ecd85ee5c'
silent! let g:plugs['nvterm'].commit = '3e43be1d0ca60cc5e2dfc2d289b06577e7e57e98'
silent! let g:plugs['oceanic-next'].commit = '09833f72d5ba23de2e8bcae18f479f326f5f677a'
silent! let g:plugs['project.nvim'].commit = '8c6bad7d22eef1b71144b401c9f74ed01526a4fb'
silent! let g:plugs['targets.vim'].commit = '642d3a4ce306264b05ea3219920b13ea80931767'
silent! let g:plugs['vim-better-whitespace'].commit = '1b22dc57a2751c7afbc6025a7da39b7c22db635d'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'
silent! let g:plugs['which-key.nvim'].commit = '4433e5ec9a507e5097571ed55c02ea9658fb268a'

PlugUpdate!

